<a href="https://colab.research.google.com/github/kragtenb/SelfDriving-RC-deep-learning/blob/main/NumPyTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Arrays and Array Creation

## Arrays
*   To make a 1D array you could use np.array([1, 2, 3 ,4])
* To fill with zeros use np.zeros((3,4)) this would be a 3x4 array of zeros
* Arange can be used to fill numbers like np.arange(5, 15, 2) for [5, 7, 9, 11, 13]
* Operations on arrays will be done element wise
** array1 + array2
* Single Elements; array[row_index, column_index]
* Slicing array[start:end] End is not included
* reshape array. Elements number must not change
** array.reshape((new_rows, new_columns)) Note requires tuple.



# Practice Tasks

Create Multidimensional Arrays:
1. Create a 3x3 NumPy array of all 5s.
2. Create a 2x3x4 array (2 layers, each layer has a 3x4 shape) with values from 1 to 24, sequentially.

arange() variations:
1. Generate numbers from 10 to 1 (descending) with a step of -2.
2. Create an array with 8 evenly spaced values between 0 and 1 (look into np.linspace()).

# 1. Create a 3x3 NumPy array of all 5s.

In [18]:
import numpy as np

array_of_fives = np.zeros((3, 3), dtype="int")
array_of_fives[:] = 5
print(array_of_fives)

all_fives = np.ones((3, 3)) * 5
print(all_fives)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


# 2. Create a 2x3x4 array (2 layers, each layer has a 3x4 shape) with values from 1 to 24, sequentially.

In [15]:
import numpy as np

one_through_twenty_four = np.arange(1, 25, 1)
reshaped_array = one_through_twenty_four.reshape((2, 3, 4))
print(reshaped_array)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


1

# 1. Generate numbers from 10 to 1 (descending) with a step of -2.

In [16]:
import numpy as np

np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

# 2. Create an array with 8 evenly spaced values between 0 and 1 (look into np.linspace()).

In [19]:
import numpy as np

np.linspace(0, 1, num=8)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

# Day 2: Array Properties and Operations

##Array Stats:

1. Create a NumPy array with some values (both positive and negative).

In [22]:
values = np.array([1, -5, 3, -2, 8, -10])

2. Calculate the mean, minimum, maximum, and standard deviation of this array using NumPy functions (search for relevant 'np' functions).

In [23]:
print(f"Mean {values.mean()}")
print(f"Min {values.min()}")
print(f"Max {values.max()}")
print(f"Std {values.std()}")

Mean -0.8333333333333334
Min -10
Max 8
Std 5.7566386797235145


## Reshaping Manipulation

1. Create a 1D array of 10 elements.

In [29]:
array_ten = np.linspace(1, 10, num=10)
array_ten

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

2. Reshape it into a 2x5 array.

In [30]:
array_ten = array_ten.reshape((2, 5))
array_ten

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

3. Reshape it back into a 1D array.

In [32]:
array_ten = array_ten.reshape((1, 10))
array_ten

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

## Advanced Arithmetic

1. Create two arrays of different shapes but compatible for broadcasting (refer to the brief mention of broadcasting earlier if needed).

In [50]:
array_1 = np.array([1, 2, 3, 4])
array_2 = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])

print(array_1.shape)
print(array_2.shape)

print(array_1 * array_2)

(4,)
(4, 4)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


2. Try adding and multiplying the arrays together.

In [ ]:
print(array_2 * array_1)

# Indexing, Slicing, and Reshaping!



In [51]:
my_2d_array = np.array([[1, 2, 3], [4, 5, 6]])

In [52]:
my_2d_array[0:2, 0:2]

array([[1, 2],
       [4, 5]])

# Practice

Image Manipulation:

1. Create a simple NumPy array representing an image with pixel values ranging from 0 to 255.

2. Select a smaller section of your "image" (as if you were cropping).

3. Invert the colors of a certain region (replace values by 255 - value).

In [55]:
import random

image = np.random.randint(1, 256, (256, 256))
image

array([[118, 215, 156, ..., 247,   7, 156],
       [ 29,  31, 164, ..., 250,  63, 127],
       [ 58, 233, 158, ..., 137,  70,  86],
       ...,
       [ 85, 179,  39, ..., 239,  90,  33],
       [ 85,  53, 101, ...,  48,  56,  32],
       [228,  48, 162, ...,  12,   2,  82]])

In [59]:
crop_bottom_3x3 = image[-3:, -3:]
crop_bottom_3x3

array([[239,  90,  33],
       [ 48,  56,  32],
       [ 12,   2,  82]])

In [60]:
crop_bottom_3x3 = 255 - crop_bottom_3x3
crop_bottom_3x3

array([[ 16, 165, 222],
       [207, 199, 223],
       [243, 253, 173]])

In [61]:
image[-3:, -3:] = crop_bottom_3x3
image

array([[118, 215, 156, ..., 247,   7, 156],
       [ 29,  31, 164, ..., 250,  63, 127],
       [ 58, 233, 158, ..., 137,  70,  86],
       ...,
       [ 85, 179,  39, ...,  16, 165, 222],
       [ 85,  53, 101, ..., 207, 199, 223],
       [228,  48, 162, ..., 243, 253, 173]])

# Striding:

1. Create a 1D NumPy array.
2. Use slicing with a step to select every other element.
3. Reverse the order of the elements in the array using slicing.

In [63]:
array = np.random.randint(1, 50, 20)
array

array([15, 35, 45, 29, 19, 29, 23, 27, 39, 43, 23, 39, 11, 20,  6, 22, 24,
       16, 26, 19])

In [66]:
array[1::2]

array([35, 29, 29, 27, 43, 39, 20, 22, 16, 19])

In [74]:
array[-1::-1]

array([19, 26, 16, 24, 22,  6, 20, 11, 39, 23, 43, 39, 27, 23, 29, 19, 29,
       45, 35, 15])